#!/bin/sh

wallpaper_folder=$HOME/Pictures/wallpapers
wallpaper_default=$HOME/.local/share/default_wallpaper


wallpaper_location="$(ls $wallpaper_folder | wofi -n --show dmenu)"

# echo "$wallpaper_folder/$wallpaper_location"

if [[ -d $wallpaper_folder/$wallpaper_location ]]; then
    # echo "$wallpaper_folder/$wallpaper_location is a directory"
    wallpaper_temp="$wallpaper_location"
    # wallpaper_location="$(ls $wallpaper_folder/$wallpaper_location | wofi -n --show dmenu)"
elif [[ -f $wallpaper_folder/$wallpaper_location ]]; then
	rm -rf $wallpaper_default
	cp -r $wallpaper_folder/$wallpaper_temp/$wallpaper_location $wallpaper_default
	wall-change $wallpaper_folder/$wallpaper_temp/$wallpaper_location
else
    # echo "$wallpaper_folder/$wallpaper_location is not valid"
    exit 1
fi





